// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.25.3
// source: models/types.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_IntList
	//	*Message_ObjectData
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_models_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_models_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_models_types_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetIntList() *Positions {
	if x != nil {
		if x, ok := x.Payload.(*Message_IntList); ok {
			return x.IntList
		}
	}
	return nil
}

func (x *Message) GetObjectData() *GameState {
	if x != nil {
		if x, ok := x.Payload.(*Message_ObjectData); ok {
			return x.ObjectData
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_IntList struct {
	IntList *Positions `protobuf:"bytes,3,opt,name=int_list,json=intList,proto3,oneof"`
}

type Message_ObjectData struct {
	ObjectData *GameState `protobuf:"bytes,4,opt,name=object_data,json=objectData,proto3,oneof"`
}

func (*Message_IntList) isMessage_Payload() {}

func (*Message_ObjectData) isMessage_Payload() {}

type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Food          int32                  `protobuf:"varint,1,opt,name=food,proto3" json:"food,omitempty"`
	Snakes        []*Snake               `protobuf:"bytes,2,rep,name=snakes,proto3" json:"snakes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_models_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_models_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_models_types_proto_rawDescGZIP(), []int{1}
}

func (x *GameState) GetFood() int32 {
	if x != nil {
		return x.Food
	}
	return 0
}

func (x *GameState) GetSnakes() []*Snake {
	if x != nil {
		return x.Snakes
	}
	return nil
}

type Snake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []int32                `protobuf:"varint,1,rep,packed,name=body,proto3" json:"body,omitempty"` // e.g. [1, 2, 3]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snake) Reset() {
	*x = Snake{}
	mi := &file_models_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snake) ProtoMessage() {}

func (x *Snake) ProtoReflect() protoreflect.Message {
	mi := &file_models_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snake.ProtoReflect.Descriptor instead.
func (*Snake) Descriptor() ([]byte, []int) {
	return file_models_types_proto_rawDescGZIP(), []int{2}
}

func (x *Snake) GetBody() []int32 {
	if x != nil {
		return x.Body
	}
	return nil
}

type Positions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []int32                `protobuf:"varint,1,rep,packed,name=body,proto3" json:"body,omitempty"` // e.g. [1, 2, 3]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Positions) Reset() {
	*x = Positions{}
	mi := &file_models_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Positions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Positions) ProtoMessage() {}

func (x *Positions) ProtoReflect() protoreflect.Message {
	mi := &file_models_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Positions.ProtoReflect.Descriptor instead.
func (*Positions) Descriptor() ([]byte, []int) {
	return file_models_types_proto_rawDescGZIP(), []int{3}
}

func (x *Positions) GetBody() []int32 {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_models_types_proto protoreflect.FileDescriptor

const file_models_types_proto_rawDesc = "" +
	"\n" +
	"\x12models/types.proto\"\x80\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12'\n" +
	"\bint_list\x18\x03 \x01(\v2\n" +
	".PositionsH\x00R\aintList\x12-\n" +
	"\vobject_data\x18\x04 \x01(\v2\n" +
	".GameStateH\x00R\n" +
	"objectDataB\t\n" +
	"\apayload\"?\n" +
	"\tGameState\x12\x12\n" +
	"\x04food\x18\x01 \x01(\x05R\x04food\x12\x1e\n" +
	"\x06snakes\x18\x02 \x03(\v2\x06.SnakeR\x06snakes\"\x1b\n" +
	"\x05Snake\x12\x12\n" +
	"\x04body\x18\x01 \x03(\x05R\x04body\"\x1f\n" +
	"\tPositions\x12\x12\n" +
	"\x04body\x18\x01 \x03(\x05R\x04bodyB\x1aZ\x18gorilla_websocket/modelsb\x06proto3"

var (
	file_models_types_proto_rawDescOnce sync.Once
	file_models_types_proto_rawDescData []byte
)

func file_models_types_proto_rawDescGZIP() []byte {
	file_models_types_proto_rawDescOnce.Do(func() {
		file_models_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_types_proto_rawDesc), len(file_models_types_proto_rawDesc)))
	})
	return file_models_types_proto_rawDescData
}

var file_models_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_models_types_proto_goTypes = []any{
	(*Message)(nil),   // 0: Message
	(*GameState)(nil), // 1: GameState
	(*Snake)(nil),     // 2: Snake
	(*Positions)(nil), // 3: Positions
}
var file_models_types_proto_depIdxs = []int32{
	3, // 0: Message.int_list:type_name -> Positions
	1, // 1: Message.object_data:type_name -> GameState
	2, // 2: GameState.snakes:type_name -> Snake
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_models_types_proto_init() }
func file_models_types_proto_init() {
	if File_models_types_proto != nil {
		return
	}
	file_models_types_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_IntList)(nil),
		(*Message_ObjectData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_types_proto_rawDesc), len(file_models_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_types_proto_goTypes,
		DependencyIndexes: file_models_types_proto_depIdxs,
		MessageInfos:      file_models_types_proto_msgTypes,
	}.Build()
	File_models_types_proto = out.File
	file_models_types_proto_goTypes = nil
	file_models_types_proto_depIdxs = nil
}
